### ISSUE TITLE
automate game ID crosswalk and advanced passing

### ISSUE THREAD

**Issue by guga31bb** [nflverse/pfr_scrapR#1]
- Run once per week: https://github.com/guga31bb/pfr_scrapR/blob/master/R/pfr_game_id_crosswalk.R
- Run once per day during season: https://github.com/guga31bb/pfr_scrapR/blob/master/R/passing.R

To add: script to get snap counts for an ongoing season

**Comment by mrcaseb** [comment]
Which day would be the "once per week" script? Wednesday? 
And runtime over night?

**Comment by guga31bb** [comment]
Maybe Tuesday overnight (ie very early Wed morning)?

**Comment by mrcaseb** [comment]
Yep sounds good
