### ISSUE TITLE
Game ID crosswalk workflow failing

### ISSUE THREAD

**Issue by guga31bb** [nflverse/pfr_scrapR#11]
```Error: Error in loadNamespace(x) : there is no package called ‘nflreadr’```

https://github.com/nflverse/pfr_scrapR/runs/3618519985?check_suite_focus=true

**Comment by mrcaseb** [comment]
Fixed with https://github.com/nflverse/pfr_scrapR/commit/3eac7d03aab59458d4021243c84f2ee31a373ad4
