### ISSUE TITLE
Missing 2018 passing data in nflreadr:load_pfr_advstats

### ISSUE THREAD

**Issue by twainw** [nflverse/pfr_scrapR#17]
Hi, 
I want to use PFR's advanced passing stats from seasons 2018 to 2021, but the loaded dataset consists rows only 2019 to 2021. Reinstalling the package did not fix the issue. 

Here is the code I'm using to load PFR data. 
`load_pfr_advstats(seasons = 2018:2021, stat_type = 'pass', summary_level = 'season'). `

**Comment by mrcaseb** [comment]
2018 will be available soon, however, please note that some of the data is missing in 2018, e.g. bats, on target throws, or play types
