### ISSUE TITLE
Duplicated pfr_id on the combine dataset

### ISSUE THREAD

**Issue by Adeiko** [nflverse/pfr_scrapR#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

1.3.1

### Describe the bug

Some players in the combine dataset have duplicated pfr_id

### Reprex

```r
nflreadr::load_combine() |> 
  dplyr::group_by(pfr_id) |>
  dplyr::summarise(dupes=dplyr::n()) |> 
  dplyr::filter(dupes > 1,!is.na(pfr_id))
#> # A tibble: 18 × 2
#>    pfr_id   dupes
#>    <chr>    <int>
#>  1 BrowCh03     2
#>  2 BrowPh00     2
#>  3 CartCh00     2
#>  4 ColeJu01     2
#>  5 DaviBu99     2
#>  6 EdwaMi01     2
#>  7 GreeMi00     2
#>  8 HawkCh00     2
#>  9 JohnDe25     2
#> 10 JoneCh09     2
#> 11 SamuSt01     2
#> 12 SmitKe03     2
#> 13 ThomPh00     2
#> 14 WashTo00     2
#> 15 WebbJe00     2
#> 16 WillBo00     2
#> 17 WillJa96     2
#> 18 WilsTr00     2
```

### Expected Behavior

unique pfr_id

### nflverse_sitrep

```r
nflverse_sitrep()
── System Info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• R version 4.2.1 (2022-06-23 ucrt)   • Running under: Windows 10 x64 (build 19043)
── nflverse Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• nflreadr (1.3.1)       • nflseedR (1.1.0)       • nflplotR (1.1.0)  
• nflfastR (4.4.0.9010)  • nfl4th   (1.0.2.9002)  • nflverse (1.0.2)  
── nflverse Options ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• nflreadr.verbose: FALSE
── nflverse Dependencies ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• askpass     (1.1)         • gtable      (0.3.1)     • progressr    (0.11.0)   
• bit         (4.0.4)       • hms         (1.1.2)     • proto        (1.0.0)    
• bit64       (4.0.5)       • httr        (1.4.4)     • purrr        (0.3.4)    
• cachem      (1.0.6)       • isoband     (0.2.5)     • R6           (2.5.1)    
• cli         (3.4.1)       • janitor     (2.1.0)     • rappdirs     (0.3.3)    
• clipr       (0.8.0)       • jsonlite    (1.8.2)     • RColorBrewer (1.1-3)    
• codetools   (0.2-18)      • labeling    (0.4.2)     • Rcpp         (1.0.9)    
• colorspace  (2.0-3)       • lattice     (0.20-45)   • readr        (2.1.3)    
• cpp11       (0.4.2)       • lifecycle   (1.0.2)     • rlang        (1.0.6)    
• crayon      (1.5.2)       • listenv     (0.8.0)     • rstudioapi   (0.14)     
• curl        (4.3.2)       • lubridate   (1.8.0)     • scales       (1.2.1)    
• data.table  (1.14.2)      • magick      (2.7.3)     • snakecase    (0.11.0)   
• digest      (0.6.29)      • magrittr    (2.0.3)     • stringi      (1.7.8)    
• dplyr       (1.0.10)      • MASS        (7.3-58.1)  • stringr      (1.4.1)    
• ellipsis    (0.3.2)       • Matrix      (1.5-1)     • sys          (3.4)      
• fansi       (1.0.3)       • memoise     (2.0.1)     • tibble       (3.1.8)    
• farver      (2.1.1)       • mgcv        (1.8-40)    • tidyr        (1.2.1)    
• fastmap     (1.1.0)       • mime        (0.12)      • tidyselect   (1.1.2)    
• fastrmodels (1.0.2.9001)  • munsell     (0.5.0)     • tzdb         (0.3.0)    
• furrr       (0.3.1)       • nlme        (3.1-159)   • utf8         (1.2.2)    
• future      (1.28.0)      • openssl     (2.0.3)     • vctrs        (0.4.2)    
• generics    (0.1.3)       • parallelly  (1.32.1)    • viridisLite  (0.4.1)    
• ggplot2     (3.3.6)       • pillar      (1.8.1)     • vroom        (1.6.0)    
• globals     (0.16.1)      • pkgconfig   (2.0.3)     • withr        (2.5.0)    
• glue        (1.6.2)       • prettyunits (1.1.1)     • xgboost      (1.6.0.1)  
• gsubfn      (0.7)         • progress    (1.2.2)
```

**Comment by Adeiko** [comment]
Some more info on the guys: 

Most of this is PFR problem, they have incorrectly linked some players 

Chris Brown <- when you click on the player it links to the RB, but it was an OL really that is not really in the PFR db. BrowCh03
https://www.pro-football-reference.com/draft/2001-combine.htm
https://en.wikipedia.org/wiki/Chris_Brown_(offensive_lineman)

Corey Brown <- Same problem, in the 2001 combine page it links to a WR from 2014. He is not there in the PFR DB

Chris Carter <- Same problem, it does not exist in PFR db really
https://www.pro-football-reference.com/draft/2010-combine.htm

Buster Davis <- "DaviBu99" corresponds to the ILB, the WR is really "DaviCr00" called Craig Davis

Mike edwards <- The correct one is the guy drafted in 2019 S from Kentycky. The one from 2013 has no pfr id. 

Mike Green <- The correct one is the fullback, the Safety has no PFR page. 

Chris Hawkins <- The correct one is the one with cfb-id "chris-hawkins-1" from LSU  The other has no PFR id

Derrick Johnson <- JohnDe25 is the OLB, JohnDe24 is the CB

Chris Jones <- The WR from alabama has no PFR ID

Stanford Samuels <- The CB from 2004 has no PFR id 

Keith Smith <- I'm too confused, Neither of them is SmitKe03, since SmitKe03 is from 2022.

Phillip Thomas <- ThomPh00 is the one from Fresno in 2013, the one from syracuse has no PFR ID

Tony Washington <- WashTo00 is the one from 20155, the one from 2010 has no PFR id 

Jeff Webb <- the punter has no pFR id, WebbJe00 is the WR 

Boo Williams <- WillBo00 is the TE from 2001, the RB has no ID

Jack Williams <- WillJa96 is the CB from 2008, the safety has no PFR ID

Travis Wilson <- WilsTr00 is the WR from Oklahoma, the FB has no PFR ID

**Comment by mrcaseb** [comment]
Can confirm all of these are problems on PFR site. Fixing this would require a lot of manual work so I doubt we will do it. Thanks for looking into this @Adeiko!

**Comment by mrcaseb** [comment]
Here's a reprex to compute all problematic IDs and more information
``` r
nflreadr::load_combine() |> 
  dplyr::filter(!is.na(pfr_id)) |> 
  dplyr::filter(dplyr::n() > 1, .by = pfr_id) |> 
  dplyr::select(season, draft_year, player_name, pfr_id, pos, school, cfb_id) |> 
  dplyr::arrange(pfr_id) |> 
  gt::gt(groupname_col = "pfr_id") |> 
  gt::sub_missing() |> 
  gtExtras::gt_theme_538()
```
![image](https://github.com/nflverse/nflverse-pfr/assets/38586519/1e662e21-8471-447d-adce-5ba270842783)
