### ISSUE TITLE
[BUG] 2024 data - some games missing, some mis-mapped columns

### ISSUE THREAD

**Issue by alecglen** [nflverse/pfr_scrapR#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

NA

### Describe the bug

There seems to be some issues with the 2024 `pfr_advstats`.

1. The Sunday and MNF games haven't populated yet.
2. While confirming that, I noticed that the Thursday and Friday game didn't map columns correctly. (at least for rushing, haven't looked at the others): <img width="1557" alt="image" src="https://github.com/user-attachments/assets/10f5d826-cd3e-4878-af9e-88bd820898c0">

### Reprex

```r
https://github.com/nflverse/nflverse-data/releases/tag/pfr_advstats
```

### Expected Behavior

NA

### nflverse_sitrep

```r
NA
```

### Additional context

Reported in https://github.com/nflverse/nfl_data_py/issues/100

**Comment by alecglen** [comment]
Also just noticed in the screenshot, a `receiving_broken_tackles` column snuck into the rushing file somehow?

**Comment by mrcaseb** [comment]
> Also just noticed in the screenshot, a `receiving_broken_tackles` column snuck into the rushing file somehow?

I checked the code and I am sure that's actually a bug that always has been there. It's related to the way we select columns for different stat types.
https://github.com/nflverse/nflverse-pfr/blob/f99ff94f614cce9e6927da82e1fc251b0c5946a8/auto/update_adv_stats.R#L143-L150

There are similar problems in the other stat types as well.

**Comment by mrcaseb** [comment]
All Sunday games are online now. ~~MNF still returning empty~~

EDIT: MNF is online now

**Comment by mrcaseb** [comment]
RE: false columns

I don't really like the codebase in this repo and we should probably rewrite some things to be more flexible and better maintainable. Since that's some work we probably won't do it anytime soon and keep it as is as long as it is functioning.

**Comment by alecglen** [comment]
@mrcaseb I think a fix is still needed in the near term; it's not functioning correctly. Specifically in the screenshot:
- `rush_yards_before_contact` values are actually total rushing yards
- `rush_yards_before_contact_avg` was also derived from the total rushing yards
- The YAC and broken tackles values appear to be lost altogether.

**Comment by Laneville** [comment]
yeah I'm seeing the same issues with the updated data. Do we know what the issue is?

**Comment by mrcaseb** [comment]
Turned out that it must have been an issue on PFR side. I have re-scraped the games and data looks clean now.
![image](https://github.com/user-attachments/assets/2b45db45-6640-430e-b31f-cd519b451f1d)
